services:
  postgres:
    container_name: postgres-sql-monument
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456789
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: MonumentExplorerDb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - spring-network
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "5000:5000"
    environment:
      - ENABLED_LANGUAGES=en,es,fr,de,ar,zh,ru

networks:
  spring-network:
    driver: bridge

volumes:
  postgres:
  pgadmin-data:
