spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/MonumentExplorerDb
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql

libretranslate:
  url: http://localhost:5000

server:
  port: 8081




